In [1]:
import pandas as pd

In [2]:
base_ori = pd.read_csv("./Evaluation/bert_dummy_output/onnew_neg_bert_base_raw_score.csv")
stancy_ori = pd.read_csv("./Evaluation/bert_dummy_output/onnew_neg_bert_cons_epoch5_raw_score.csv")
sia_ori = pd.read_csv("./Evaluation/bert_dummy_output/new_neg_bert_sia_cos_bs24_lr2e_5_epoch30_raw_score.csv")

In [3]:
base_opp = pd.read_csv("./Evaluation/antonym_output/onnew_neg_opposite_perspectives_bert_base_raw_score.csv")
stancy_opp = pd.read_csv("./Evaluation/antonym_output/onnew_neg_opposite_perspectives_bert_cons_epoch5_raw_score.csv")
sia_opp = pd.read_csv("./Evaluation/antonym_output/new_neg_opposite_perspectives_bert_sia_cos_bs24_lr2e_5_epoch30_raw_score.csv")

In [4]:
base_ori.rename(columns={'undermine_score':'undermine_ori','support_score':'support_ori', 'predict_label':'predict_ori', 'gold':'gold_ori' },inplace=True)
stancy_ori.rename(columns={'undermine_score':'undermine_ori','support_score':'support_ori', 'predict_label':'predict_ori', 'gold':'gold_ori' },inplace=True)
sia_ori.rename(columns={'undermine_score':'undermine_ori','support_score':'support_ori', 'predict_label':'predict_ori', 'gold':'gold_ori' },inplace=True)

In [5]:
base_ori

undermine_ori  support_ori  predict_ori  gold_ori
0         -1.104498     1.399804            1         1
1         -1.272779     1.762252            1         0
2         -3.644970     4.152650            1         1
3         -2.216542     2.491149            1         1
4         -1.375447     1.548147            1         1
...             ...          ...          ...       ...
2397      -3.182455     3.654049            1         0
2398      -3.327009     3.956924            1         0
2399       2.547285    -2.342756            0         1
2400       4.318411    -4.532940            0         1
2401       3.814458    -3.830362            0         1

[2402 rows x 4 columns]

In [6]:
base_opp.rename(columns={'undermine_score':'undermine_opposite','support_score':'support_opposite', 'predict_label':'predict_opposite', 'gold':'gold_opposite' },inplace=True)
stancy_opp.rename(columns={'undermine_score':'undermine_opposite','support_score':'support_opposite', 'predict_label':'predict_opposite', 'gold':'gold_opposite' },inplace=True)
sia_opp.rename(columns={'undermine_score':'undermine_opposite','support_score':'support_opposite', 'predict_label':'predict_opposite', 'gold':'gold_opposite' },inplace=True)

In [7]:
base_opp

undermine_opposite  support_opposite  predict_opposite  gold_opposite
0              -0.886965          0.841433                 1              0
1              -0.860910          1.316047                 1              1
2              -1.822727          2.088518                 1              0
3               0.655416         -0.446708                 0              0
4               2.253140         -1.940499                 0              0
...                  ...               ...               ...            ...
2397            1.359215         -1.050081                 0              1
2398            0.252174         -0.473792                 0              1
2399            0.010933         -0.189821                 0              0
2400            1.690355         -1.151755                 0              0
2401            0.437417         -0.639354                 0              0

[2402 rows x 4 columns]

In [8]:
base_comb = pd.concat([base_ori,base_opp],axis=1)
stancy_comb = pd.concat([stancy_ori,stancy_opp],axis=1)
sia_comb = pd.concat([sia_ori,sia_opp],axis=1)

In [9]:
sia_comb

undermine_ori  support_ori  predict_ori  gold_ori  undermine_opposite  \
0         -5.659800     8.410093            1         1           -5.462558   
1          6.123189    -4.846788            0         0           -5.647560   
2          2.609766    -1.099538            0         1            8.459325   
3          5.133741    -3.710541            0         1            4.360720   
4         -3.736549     6.248719            1         1            4.862767   
...             ...          ...          ...       ...                 ...   
2397       1.204155    -1.608856            0         0            0.869449   
2398       1.730360    -2.154261            0         0           -5.287125   
2399      -3.720044     2.957295            1         1            1.710512   
2400      -3.745683     2.977419            1         1            1.679382   
2401      -2.807508     1.740879            1         1           -2.779148   

      support_opposite  predict_opposite  gold_opposite  
0             8.178183                 1              0  
1             8.411349                 1              1  
2            -7.760164                 0              0  
3            -2.757958                 0              0  
4            -3.312057                 0              0  
...                ...               ...            ...  
2397         -1.214664                 0              1  
2398          4.567977                 1              1  
2399         -2.128206                 0              0  
2400         -2.103550                 0              0  
2401          1.708421                 1              0  

[2402 rows x 8 columns]

In [10]:
base_stable = base_comb[base_comb.predict_ori!=base_comb.predict_opposite]
stancy_stable = stancy_comb[stancy_comb.predict_ori!=stancy_comb.predict_opposite]
sia_stable = sia_comb[sia_comb.predict_ori!=sia_comb.predict_opposite]

In [11]:
sia_stable

undermine_ori  support_ori  predict_ori  gold_ori  undermine_opposite  \
1          6.123189    -4.846788            0         0           -5.647560   
4         -3.736549     6.248719            1         1            4.862767   
5         -5.648978     8.431259            1         1            4.233076   
6         -5.597363     8.379188            1         1            4.695032   
8         -5.597363     8.379188            1         1            4.695032   
...             ...          ...          ...       ...                 ...   
2394       1.556710    -2.007751            0         0           -4.243136   
2395       1.994757    -2.375398            0         0           -5.797869   
2398       1.730360    -2.154261            0         0           -5.287125   
2399      -3.720044     2.957295            1         1            1.710512   
2400      -3.745683     2.977419            1         1            1.679382   

      support_opposite  predict_opposite  gold_opposite  
1             8.411349                 1              1  
4            -3.312057                 0              0  
5            -2.612038                 0              0  
6            -3.077996                 0              0  
8            -3.077996                 0              0  
...                ...               ...            ...  
2394          3.589785                 1              1  
2395          5.096775                 1              1  
2398          4.567977                 1              1  
2399         -2.128206                 0              0  
2400         -2.103550                 0              0  

[1298 rows x 8 columns]

In [12]:
from sklearn.metrics import f1_score,precision_score,recall_score

In [13]:
precision_score(base_stable.gold_ori,base_stable.predict_ori)

0.7521263669501823

In [14]:
recall_score(base_stable.gold_ori,base_stable.predict_ori)

0.8102094240837696

In [15]:
f1_score(base_stable.gold_ori,base_stable.predict_ori)

0.7800882167611846

In [16]:
f1_score(base_comb.gold_ori,base_comb.predict_ori)

0.7020408163265306

In [17]:
f1_score(base_stable.gold_opposite,base_stable.predict_opposite)

0.661493695441319

In [18]:
f1_score(base_comb.gold_opposite,base_comb.predict_opposite)

0.4692346173086543

In [19]:
precision_score(stancy_stable.gold_ori,stancy_stable.predict_ori)

0.7835909631391201

In [20]:
recall_score(stancy_stable.gold_ori,stancy_stable.predict_ori)

0.8659658344283837

In [21]:
f1_score(stancy_stable.gold_ori,stancy_stable.predict_ori)

0.822721598002497

In [22]:
f1_score(stancy_comb.gold_ori,stancy_comb.predict_ori)

0.7572347266881029

In [23]:
f1_score(stancy_stable.gold_opposite,stancy_stable.predict_opposite)

0.7325800376647834

In [24]:
f1_score(stancy_comb.gold_opposite,stancy_comb.predict_opposite)

0.4891304347826087

In [25]:
precision_score(sia_stable.gold_ori,sia_stable.predict_ori)

0.8305732484076433

In [26]:
recall_score(sia_stable.gold_ori,sia_stable.predict_ori)

0.8787061994609164

In [27]:
f1_score(sia_stable.gold_ori,sia_stable.predict_ori)

0.85396201702685

In [28]:
f1_score(sia_comb.gold_ori,sia_comb.predict_ori)

0.7878787878787877

In [29]:
f1_score(sia_stable.gold_opposite,sia_stable.predict_opposite)

0.7913938260056127

In [30]:
# f1_score(sia_comb.gold_opposite,sia_comb.predict_opposite)

0.5202639019792649

In [1]:
import torch

In [8]:
torch.tensor([1,0,1])

tensor([1, 0, 1])

In [149]:
x=torch.tensor([0,1,1,0,0])
y=torch.tensor([2.1,3.5,2.7,5.6,8.8])
z=torch.tensor([-2.1,-3.5,-2.7,-5.6,-8.8])

In [150]:
k=0
index=[]
for i in x:
    k=k+1
    if i ==0:
        print(k)
        index.append(k)

1
4
5


In [151]:
index

[1, 4, 5]

In [152]:
import copy

In [160]:
y_inter=y.clone().detach()
z_inter=copy.deepcopy(z)
y_inter2=copy.deepcopy(y)
z_inter2=copy.deepcopy(z)

In [161]:
y_inter

tensor([2.1000, 3.5000, 2.7000, 5.6000, 8.8000])

In [162]:
for l in index:
    y_inter[l-1],z_inter[l-1]= z_inter[l-1],y_inter[l-1]

In [163]:
y_inter

tensor([-2.1000,  3.5000,  2.7000, -5.6000, -8.8000])

In [164]:
y

tensor([2.1000, 3.5000, 2.7000, 5.6000, 8.8000])

In [143]:
for l in index:
    z_inter2[l-1],y_inter2[l-1]= y_inter2[l-1],z_inter2[l-1]

In [148]:
z_inter2

tensor([ 2.1000, -3.5000, -2.7000,  5.6000,  8.8000])

In [62]:
y=torch.tensor([2.1,3.5,2.7,5.6,8.8])
z=torch.tensor([-2.1,-3.5,-2.7,-5.6,-8.8])
for l in index:
    z[l-1],y[l-1]=y[l-1],z[l-1]

In [63]:
z

tensor([ 2.1000, -3.5000, -2.7000,  5.6000,  8.8000])

In [64]:
y

tensor([2.1000, 3.5000, 2.7000, 5.6000, 8.8000])

In [10]:
1-x

tensor([0, 2, 0])

In [4]:
x[1]

tensor(-1)